"""Custom exception hierarchy for the FO-X 5M Quantitative Engine.

Every domain-specific error inherits from FOXBaseException to allow clean
error trapping, root-cause diagnostics, and graceful recovery.
"""

from typing import Any, Dict, Optional


class FOXBaseException(Exception):
    """Base exception class for all errors generated by the FO-X 5M system."""

    def __init__(self, message: str, details: Optional[Dict[str, Any]] = None) -> None:
        super().__init__(message)
        self.message = message
        self.details = details or {}

    def __str__(self) -> str:
        if self.details:
            return f"{self.message} | Details: {self.details}"
        return self.message


class ConfigurationError(FOXBaseException):
    """Raised when there is an invalid configuration, missing key, or parse failure."""
    pass


class DataValidationError(FOXBaseException):
    """Raised when incoming market data violates domain rules or timestamp sequences."""
    pass


class DataProviderError(FOXBaseException):
    """Raised when a data provider fails to connect, stream, or fetch requested records."""
    pass


class FeatureCalculationError(FOXBaseException):
    """Raised when calculation of footprint, order flow, or context features fails."""
    pass


class ModelValidationError(FOXBaseException):
    """Raised when Pydantic model validation fails or deserialization is corrupted."""
    pass


class BacktestError(FOXBaseException):
    """Raised when backtesting replay or execution simulation encounters an invalid state."""
    pass


class DecisionEngineError(FOXBaseException):
    """Raised when decision logic, scoring, or EV evaluation encounters a fatal error."""
    pass
